ClickHouse/spark-clickhouse-connector

clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/BaseClusterWriteSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/ClickHouseClusterReadSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/SparkClickHouseClusterTestHelper.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseDataTypeSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/SparkClickHouseSingleTestHelper.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/SchemaUtils.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/read/ClickHouseReader.scala

Support Array type

---

clickhouse-spark-32/src/main/scala/org/apache/spark/sql/clickhouse/ExprUtils.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/write/WriteJobDescription.scala

Also sort records by shardingKey and partitionKey before writing

---

clickhouse-core/src/main/scala/xenon/clickhouse/format/JSONOutputFormat.scala
clickhouse-core/src/main/scala/xenon/clickhouse/grpc/GrpcNodeClient.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/ClickHouseClusterReadSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
clickhouse-spark-32/src/main/scala/org/apache/spark/sql/clickhouse/ExprUtils.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/SQLHelper.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/read/ClickHouseRead.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/read/ClickHouseReader.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/read/ScanJobDescription.scala

Implement SupportsPushDownAggregates

---

clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
clickhouse-spark-32/src/main/scala/org/apache/spark/sql/clickhouse/ExprUtils.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseTable.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/SQLHelper.scala

Close #29
Limitations:
- Does not support `Distributed` tables
- Does not support `loadPartitionMetadata`

Implement SupportsPartitionManagement

---

clickhouse-core/src/main/scala/xenon/clickhouse/parse/AstVisitor.scala
clickhouse-core/src/test/scala/xenon/clickhouse/parse/SQLParserSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseTable.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/read/InputPartitions.scala

Feature: support ClickHouse table with multi partition columns

---

clickhouse-core/src/main/scala/xenon/clickhouse/parse/AstVisitor.scala
clickhouse-core/src/main/scala/xenon/clickhouse/spec/TableEngineSpec.scala
clickhouse-core/src/test/scala/xenon/clickhouse/parse/SQLParserSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseTable.scala

Support read table order by multi columns

---

clickhouse-core/src/main/scala/xenon/clickhouse/parse/AstVisitor.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/ClusterShardByRandSuite.scala
clickhouse-spark-32/src/main/scala/org/apache/spark/sql/clickhouse/ExprUtils.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseTable.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/write/ClickHouseWrite.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/write/WriteJobDescription.scala

Support read and write distributed table sharding by rand()

---

clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/ClusterPartitionManagementSuite.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseTable.scala

Implement SupportsPartitionManagement on Distributed table

---

clickhouse-spark-32/src/main/scala/xenon/clickhouse/SchemaUtils.scala

Support Spark FloatType/DoubleType

---

clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseDataTypeSuite.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/SchemaUtils.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/read/ClickHouseReader.scala
clickhouse-spark-32/src/test/scala/xenon/clickhouse/SchemaUtilsSuite.scala

Support Map type

---

clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/BaseSparkSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/ClusterDeleteSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseTable.scala

Implement TruncatableTable

---

clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/cluster/ClusterDeleteSuite.scala
clickhouse-spark-32-integration/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala
clickhouse-spark-32/src/main/scala/xenon/clickhouse/ClickHouseTable.scala

Implement SupportsDelete

---

gradle.properties

close #98
Please refer to the following attachs for details.

Upgrade testcntainers_scala_version to 0.40.7

---

spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala

```
CREATE { DATABASE | SCHEMA } [ IF NOT EXISTS ] database_name
WITH DBPROPERTIES ( cluster = default )
```

Support create database on cluster

---

.github/workflows/tpcds.yml
build.gradle
docker/image/scc-spark.Dockerfile
spark-3.2/build.gradle
spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/TPCDSHelper.scala
spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/cluster/TPCDSClusterSuite.scala
spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/single/TPCDSSuite.scala
spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala

TPCDS: Add TPC-DS 1GB test

---

spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/read/ClickHouseReader.scala
spark-3.3/clickhouse-spark-it/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/read/ClickHouseRead.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/read/ClickHouseReader.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/read/ScanJobDescription.scala

Implement SupportsPushDownLimit

---

spark-3.2/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala
spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala

Initial support LowCardinality

---

build.gradle
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/WriteDistributionAndOrderingSuite.scala

And also enable tests which were failed because of SPARK-39313

Test against Spark 3.3.0 rc5

---

docs/configurations/02_sql_configurations.md
spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala
spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SparkOptions.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/write/ClickHouseWrite.scala

Add conf spark.clickhouse.write.repartitionStrictly

---

spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/cluster/SparkClickHouseClusterMixin.scala
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/SparkClickHouseSingleMixin.scala
spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala
spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SparkOptions.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/write/ClickHouseWrite.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/write/ClickHouseWriter.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/write/format/ClickHouseArrowStreamWriter.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/write/format/ClickHouseJsonEachRowWriter.scala

Spark 3.3: Support writing format ArrowStream

---

build.gradle
spark-3.2/build.gradle
spark-3.3/build.gradle

Apache Kyuubi v1.6.0-incubating RC1 vote channel
https://www.mail-archive.com/dev@kyuubi.apache.org/msg02565.html
Kyuubi v1.6.0-incubating RC1 became v1.6.0-incubating
https://www.mail-archive.com/general@incubator.apache.org/msg78306.html

Bump Kyuubi TPC-DS Connector 1.6.0-incubating

---

docs/best_practices/01_deployment.md
docs/quick_start/02_play_with_spark_sql.md

Apache Kyuubi has graduated as a TLP 
https://github.com/apache/kyuubi/issues/4020

Docs: Remove incubating from Kyuubi reference

---

spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/SparkTest.scala
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/cluster/BaseClusterWriteSuite.scala
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/cluster/SparkClickHouseClusterTest.scala
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/ClickHouseDataTypeSuite.scala
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/ClickHouseSingleSuite.scala
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/SparkClickHouseSingleTest.scala
spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/WriteDistributionAndOrderingSuite.scala
spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/SQLHelper.scala

Fix https://github.com/housepower/spark-clickhouse-connector/issues/210

Spark: Fix timestamp value transformation

---

spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala
spark-3.3/clickhouse-spark/src/test/scala/org/apache/spark/sql/clickhouse/ClickHouseHelperSuite.scala

Backport #231 to Spark 3.3, fix #230

Spark 3.3: Fix custom options

---

spark-3.4/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/ClickHouseDataTypeSuite.scala
spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseJsonReader.scala

Spark 3.4: Fix Decimal precision in JSON mode on reading

---

spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseJsonReader.scala
spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseJsonReader.scala

Spark: Add int long bigInteger case for Decimal

---

README.md
docs/index.md
gradle.properties

Build: Bump ClickHouse Java Client 0.6.0

---

build.gradle
gradle.properties

Test Apache Spark 3.5.1 (RC2)
https://www.mail-archive.com/dev@spark.apache.org/msg31303.html

Build: Bump Spark 3.5.1

---

clickhouse-core/src/main/scala/com/clickhouse/spark/client/NodeClient.scala
spark-3.3/build.gradle
spark-3.4/build.gradle
spark-3.5/build.gradle

Adding connector metadata to useragent.

Adding connector metadata to useragent.

---

.github/workflows/publish-release.yml

Change PGP keyname

---

.github/workflows/publish-release.yml

Update action-gh-release to v2

Update action-gh-release to v2

---

examples/scala/spark-3.5/build.sbt

Update connector version in the example application 0.8.0

Update connector version in example application

---

clickhouse-core/src/main/scala/com/clickhouse/spark/client/NodeClient.scala

Protect from ArrayIndexOutOfBoundsException exception when extracting values for user agent.

Protect from ArrayIndexOutOfBoundsException exception 

---

.github/workflows/sonar.yml
build.gradle

* Add dispatch to the GitHub workflow
* Upgrade the used version

Fix SonarQube
