build.gradle, gradle.properties
JDK 11 removes `javax.annotation`
Close #64
=> Fix build error with JDK 11

clickhouse-core/src/main/scala/xenon/clickhouse/spec/TableEngineUtils.scala, spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala
For system tables, `engine_full` is empty string, we should support this case otherwise can not read the system table.
=> Fix: Fallback to UnknownTableEngineSpec when parseEngineClause failed

spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala, spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseTable.scala, spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/read/InputPartitions.scala
unquoted partition condition may cause error like below when partition column type is Date
`xenon.clickhouse.exception.ClickHouseServerException: [43] DB::Exception: Illegal types of arguments (Date, Int64) of function equals: While processing load_date = ((2022 - 4) - 12)`
=> Support partitioned by Date Type

docker/build-image.sh, docker/image/scc-base.Dockerfile
Point to AMD64/ARM64 JDK depending on the CPU arch
Replace deprecated MAINTAINER with LABEL (https://docs.docker.com/engine/reference/builder/#maintainer-deprecated)
Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
=> Use Arm64 base image when building on Linux ARM64

docs/quick_start/02_play_with_spark_sql.md, docs/quick_start/03_play_with_spark_shell.md, spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/BaseSparkSuite.scala, spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/cluster/ClusterTableManagementSuite.scala, spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/cluster/SparkClickHouseClusterTestHelper.scala, spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/single/ClickHouseSingleSuite.scala, spark-3.2/clickhouse-spark-it/src/test/scala/xenon/clickhouse/single/SparkClickHouseSingleTestHelper.scala, spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala, spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/SchemaUtils.scala
Example:
```
CREATE TABLE db.tbl_dist (
create_time TIMESTAMP NOT NULL,
y           INT       NOT NULL COMMENT 'shard key',
m           INT       NOT NULL COMMENT 'part key',
id          BIGINT    NOT NULL COMMENT 'sort key',
value       STRING
) USING ClickHouse
PARTITIONED BY (m)
TBLPROPERTIES (
cluster = 'cluster',
engine = 'Distributed',
shard_by = 'y',
local.engine = 'MergeTree()',
local.database = 'db',
local.table = 'tbl_local',
local.order_by = 'id',
local.settings.index_granularity = 8192
)
```
=> Support create Distributed table

docs/configurations/02_sql_configurations.md, spark-3.2/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/WriteDistributionAndOrderingSuite.scala, spark-3.2/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.2/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SparkOptions.scala, spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/write/WriteJobDescription.scala, spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/WriteDistributionAndOrderingSuite.scala, spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SparkOptions.scala, spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/write/WriteJobDescription.scala
Introduce two configurations to repartition/local sort by partitions optional 
- `spark.clickhouse.write.repartitionByPartition`
- `spark.clickhouse.write.localSortByPartition`
=> Make repartition/local sort by partitions optional

build.gradle, spark-3.2/build.gradle, spark-3.2/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/TestUtils.scala, spark-3.2/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/cluster/ClickHouseClusterUDFSuite.scala, spark-3.3/build.gradle, spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/TestUtils.scala, spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/cluster/ClickHouseClusterUDFSuite.scala
=> Shade Jackson to avoid class conflict

clickhouse-core/src/testFixtures/conf/clickhouse-cluster/users.xml, clickhouse-core/src/testFixtures/conf/clickhouse-single/users.xml
Suppress warning
```
(scc) ➜  spark-clickhouse-connector git:(obsolete) docker exec -it clickhouse-s1r1 bash
bash-5.1# clickhouse-client -m
ClickHouse client version 22.5.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.5.1 revision 54455.
Warnings:
* Linux is not using fast TSC clock source. Performance can be degraded.
* Some obsolete setting is changed. Check 'select * from system.settings where changed' and read the changelog.
clickhouse-s1r1 :)
```
=> Test: Remove obsolete settings

spark-3.2/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala, spark-3.2/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala, spark-3.2/clickhouse-spark/src/test/scala/org/apache/spark/sql/clickhouse/SchemaUtilsSuite.scala, spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala, spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala, spark-3.3/clickhouse-spark/src/test/scala/org/apache/spark/sql/clickhouse/SchemaUtilsSuite.scala
=> Spark: Add column comment when create clickhouse table

docs/quick_start/02_play_with_spark_sql.md, docs/quick_start/03_play_with_spark_shell.md
```
--jars JARS                 Comma-separated list of jars to include on the driver
and executor classpaths.
--packages                  Comma-separated list of maven coordinates of jars to include
on the driver and executor classpaths. Will search the local
maven repo, then maven central and any additional remote
repositories given by --repositories. The format for the
coordinates should be groupId:artifactId:version.
```
=> Fix documentation `--jars`/`--packages` usage

spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala
=> Support reading Bool type

spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseTable.scala
This pull request enables the `DROP PARTITION` operation to work with tables that have a column of type Date as partition. With this change, you can use a statement like the following to drop a partition from a ClickHouse table:
```
ALTER TABLE <table> DROP PARTITION (dt='2023-02-15')
```
where dt is a column with type Date. Before this change, attempting to drop a partition with a Date column would result in an error.
I've tested this change by running the `DROP PARTITION` operation on a table with a Date column, and I've verified that it works as expected.
Let me know if you have any questions or concerns about this change.
=> Allow dropping partitions with Date type column

clickhouse-core/src/main/scala/xenon/clickhouse/spec/NodeSpec.scala, gradle.properties, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala, spark-3.4/clickhouse-spark/src/test/scala/org/apache/spark/sql/clickhouse/ClickHouseHelperSuite.scala
Fix #230, this is for Spark 3.4, will backport to Spark 3.3 in another PR
=> Spark 3.4: Fix custom options

README.md, docs/configurations/01_catalog_configurations.md, docs/index.md, docs/internals/index.md, docs/quick_start/02_play_with_spark_sql.md, docs/quick_start/03_play_with_spark_shell.md, spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala
Due to poor support from upstream
https://github.com/ClickHouse/clickhouse-java/issues/1300#issuecomment-1483983951
> gRPC is experimental and not suitable for production. It's reserved only for testing purpose and I'll drop it someday.
=> Core: Deprecate gRPC protocol

docs/configurations/02_sql_configurations.md, spark-3.4/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseTable.scala
Fix https://github.com/housepower/spark-clickhouse-connector/issues/167
Fix https://github.com/housepower/spark-clickhouse-connector/issues/236
=> Spark 3.4: Adapt to SPARK-43390 to allow reserving schema nullability on CTAS/RTAS

spark-3.3/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/ClickHouseDataTypeSuite.scala, spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseJsonReader.scala
=> Spark 3.3: Fix Decimal precision in JSON mode on reading

spark-3.4/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala, spark-3.4/clickhouse-spark/src/test/scala/org/apache/spark/sql/clickhouse/SchemaUtilsSuite.scala
=> Spark 3.4: ClickHouse FixedString map to Spark BinaryType

spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseBinaryReader.scala, spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseJsonReader.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseBinaryReader.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseJsonReader.scala
=> Spark: Fix ArrayIndexOutOfBoundsException

spark-3.4/clickhouse-spark-it/src/test/scala/org/apache/spark/sql/clickhouse/single/WriteDistributionAndOrderingSuite.scala, spark-3.4/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ExprUtils.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseCatalog.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseTable.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/write/ClickHouseWriter.scala, spark-3.4/clickhouse-spark/src/main/scala/xenon/clickhouse/write/WriteJobDescription.scala
This is part of https://github.com/housepower/spark-clickhouse-connector/pull/253, with some tunes.
Lead-authored-by: Xinyuan Yang [yangxinyuan100@gmail.com](mailto:yangxinyuan100@gmail.com)
Co-authored-by: Cheng Pan [chengpan@apache.org](mailto:chengpan@apache.org)
=> Spark 3.4: Write supports using V2 functions for distribution and ordering

gradle.properties
This upgrading allows the developers to run docker compose related tests without the legacy `docker-compose` command in the `PATH`
https://github.com/testcontainers/testcontainers-scala/pull/260
=> Build: Bump testcontainers-scala 0.41.0 to support Docker Compose v2

spark-3.5/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseBinaryReader.scala, spark-3.5/clickhouse-spark/src/main/scala/xenon/clickhouse/read/format/ClickHouseJsonReader.scala
=> Spark 3.5: Support micro timestamp

docs/configurations/02_sql_configurations.md, spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala, spark-3.4/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.4/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala, spark-3.5/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.5/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala
Add a new configuration option `spark.clickhouse.fixedStringReadAs` to determine whether ClickHouse fixed strings should be mapped to Spark BinaryType or StringType.
[open issue here](https://github.com/housepower/spark-clickhouse-connector/issues/264)
=> Spark: Make FixedString type mapping configurable

clickhouse-core/src/testFixtures/scala/com/clickhouse/spark/base/ClickHouseSingleMixIn.scala
This PR aims to tune the code to make the test runnable on Microsoft Windows.
Unfortunately, my MacBook got damaged and I have to use a Windows machine these days, when I try to run the test with `.\gradlew.bat clean test`, I get the following errors
```
xenon.clickhouse.HashSuite *** ABORTED *** (0 milliseconds)
java.lang.RuntimeException: Unable to load a Suite class xenon.clickhouse.HashSuite that was discovered in the runpath: requirement failed: illegal path: D:\Projects\spark-clickhouse-connector\clickhouse-core-it\build\classes\scala\test      
at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:80)
at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:2 …
```
=> Test: Tune tests to support MS Windows

clickhouse-core/src/main/scala/com/clickhouse/spark/parse/AstVisitor.scala, clickhouse-core/src/main/scala/com/clickhouse/spark/spec/TableEngineSpec.scala, clickhouse-core/src/test/scala/com/clickhouse/spark/parse/SQLParserSuite.scala
Column for marking rows as deleted ([**is_deleted** column](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree#is_deleted)) of **ReplacingMergeTree**  was not anyhow handled during EngineSpec parsing resulting in runtime exception like below:
```
java.lang.IllegalArgumentException: Expect list size 0 or 1, but got 2
at xenon.clickhouse.parse.ParseUtils$.seqToOption(ParseUtils.scala:32)
at xenon.clickhouse.parse.AstVisitor.visitEngineClause(AstVisitor.scala:78)
at xenon.clickhouse.parse.SQLParser.$anonfun$parseEngineClause$1(SQLParser.scala:30)
at xenon.clickhouse.parse.SQLParser.parse(SQLParser.scala:49)
at xenon.clickhouse.parse.SQLParser.parseEngineClause(SQLParser.scala:30)
at xenon.clickhouse.spec.TableEngineUtils$.resolveTableEngine(TableEngineUti …
```
=> Fixed ReplacingMergeTree EngineSpec parsing: is_deleted column presence caused error

docs/configurations/02_sql_configurations.md, spark-3.3/clickhouse-spark/src/main/scala/com/clickhouse/spark/read/ClickHouseReader.scala, spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.4/clickhouse-spark/src/main/scala/com/clickhouse/spark/read/ClickHouseReader.scala, spark-3.4/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala, spark-3.5/clickhouse-spark/src/main/scala/com/clickhouse/spark/read/ClickHouseReader.scala, spark-3.5/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/ClickHouseSQLConf.scala
allow read with settings.
close #272
=> Spark: Support read with settings

docs/configurations/02_sql_configurations.md
=> Update configuration file

.gitignore, spark-3.3/clickhouse-spark/src/main/scala/com/clickhouse/spark/read/format/ClickHouseBinaryReader.scala, spark-3.4/clickhouse-spark/src/main/scala/com/clickhouse/spark/read/format/ClickHouseBinaryReader.scala, spark-3.5/clickhouse-spark/src/main/scala/com/clickhouse/spark/read/format/ClickHouseBinaryReader.scala
Fix binary reader String handling in Arrays and Map (e.g., `Array(String)`, `Map(String, String)`).
=> Spark: Binary reader supports String for Array/Map reading

.github/workflows/build-and-test.yml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/clickhouse-s2r2-compose.yml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/remote_servers.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r1/interserver_http_host.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r1/macros.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r2/interserver_http_host.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s1r2/macros.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r1/interserver_http_host.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r1/macros.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r2/interserver_http_host.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/s2r2/macros.xml, clickhouse-core/src/testFixtures/conf/clickhouse-cluster/zookeeper.xml, clickhouse-core/src/testFixtures/scala/com/clickhouse/spark/base/ClickHouseClusterMixIn.scala
* Updated the tested versions to those supported in https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md
* Update the default ClickHouse version (in case no version provided) to `25.3`
* Remove old `<yandex>` elements
* Place the `users.xml` config in the right path when setting up a ClickHouse cluster
close #414
=> Update supported clickhouse versions
